language: node_js

node_js:
  - 'stable'

cache:
  directories:
    - 'node_modules'

script:
  - yarn test:ci
  - yarn run build

after_sucess:
  - codecov

before_deploy:
  - cp ./build/index.html ./build/200.html

deploy:
  provider: surge
  project: ./build/
  domain: kapidoo.surge.sh
  skip_cleanup: true
